const axios = require('axios');

// Automatically retries
// In case where failing to get the data at once.
exports.getRequest = async(url, retries = 3) => {
    try{
        let result = await axios.get(url)
        if(result.status != 200 && retries > 0){
            this.getRequest(url, retries-1)
        }
        return result
    }
    catch(error){
        console.log(`Failed to get data -> ${error}`)
        if(retries > 0){
            this.getRequest(url, retries-1)
        }
        throw error(`Can't retrive data via external source.`)
    }
}
